/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductDtoAllOf } from './productDtoAllOf';
import { Product } from './product';


export interface ProductDto { 
    tags: Array<string>;
    image: string;
    price: number;
    description: string;
    shortDescription: string;
    quantity: number;
    status: ProductDto.StatusEnum;
    id?: string;
}
export namespace ProductDto {
    export type StatusEnum = 'Issued' | 'Sent' | 'Derived' | 'Returned';
    export const StatusEnum = {
        Started: 'Issued' as StatusEnum,
        Sent: 'Sent' as StatusEnum,
        Derived: 'Derived' as StatusEnum,
        Returned: 'Returned' as StatusEnum
    };
}


