/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface ProductEventUnionAnyOf1 { 
    _with: Product;
    what: ProductEventUnionAnyOf1.WhatEnum;
}
export namespace ProductEventUnionAnyOf1 {
    export type WhatEnum = 'Created';
    export const WhatEnum = {
        Created: 'Created' as WhatEnum
    };
}


