FROM node:current-alpine3.10 as build

WORKDIR /usr/src/app
COPY package*.json ./

COPY . ./
RUN npm install && npm run build

# Stage - Production
FROM nginx:1.17-alpine

EXPOSE 8080
CMD [ "node", "server.js" ]
