FROM node:current-alpine3.10 as build

WORKDIR /usr/src/app
COPY package*.json ./

COPY . ./
RUN npm install && npm run build

# Stage - Production
FROM node:current-alpine3.10

EXPOSE 8080
RUN npm run serve
