/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';


export interface IssuedEventAllOf { 
    _with: Order;
    what: IssuedEventAllOf.WhatEnum;
}
export namespace IssuedEventAllOf {
    export type WhatEnum = 'Issued';
    export const WhatEnum = {
        Issued: 'Issued' as WhatEnum
    };
}


