/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ErrorResponse { 
    message: string;
    error: ErrorResponse.ErrorEnum;
}
export namespace ErrorResponse {
    export type ErrorEnum = 'true';
    export const ErrorEnum = {
        True: 'true' as ErrorEnum
    };
}


