/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderEventUnionAllOf } from './orderEventUnionAllOf';


export interface OrderEventUnion extends OrderEventUnionAllOf { 
    _with: object;
    what: OrderEventUnion.WhatEnum;
}
export namespace OrderEventUnion {
    export type WhatEnum = 'Refunded';
    export const WhatEnum = {
        Refunded: 'Refunded' as WhatEnum
    };
}


