/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderEventUnionAnyOf3With } from './orderEventUnionAnyOf3With';


export interface OrderEventUnionAnyOf3 { 
    _with: OrderEventUnionAnyOf3With;
    what: OrderEventUnionAnyOf3.WhatEnum;
}
export namespace OrderEventUnionAnyOf3 {
    export type WhatEnum = 'Returned';
    export const WhatEnum = {
        Returned: 'Returned' as WhatEnum
    };
}


