/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestRefuntEvent } from './requestRefuntEvent';
import { PaidEvent } from './paidEvent';
import { IssuedEvent } from './issuedEvent';
import { AddressSetEvent } from './addressSetEvent';
import { RequestRefuntEventAllOfWith } from './requestRefuntEventAllOfWith';
import { SentEvent } from './sentEvent';
import { RefundEvent } from './refundEvent';


export interface OrderEventUnion { 
    who: string;
    _with: RequestRefuntEventAllOfWith;
    what: OrderEventUnion.WhatEnum;
}
export namespace OrderEventUnion {
    export type WhatEnum = 'RefundRequested';
    export const WhatEnum = {
        RefundRequested: 'RefundRequested' as WhatEnum
    };
}


