/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderEventUnionAnyOf } from './orderEventUnionAnyOf';
import { OrderEventUnionAnyOf3 } from './orderEventUnionAnyOf3';
import { OrderEventUnionAnyOf2 } from './orderEventUnionAnyOf2';
import { OrderEventUnionAnyOf1 } from './orderEventUnionAnyOf1';
import { OrderEventUnionAnyOf3With } from './orderEventUnionAnyOf3With';


export interface OrderEventUnion { 
    _with: OrderEventUnionAnyOf3With;
    what: OrderEventUnion.WhatEnum;
}
export namespace OrderEventUnion {
    export type WhatEnum = 'Returned';
    export const WhatEnum = {
        Returned: 'Returned' as WhatEnum
    };
}


