/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaidEventAllOf } from './paidEventAllOf';
import { PaidEventAllOfWith } from './paidEventAllOfWith';
import { UserBaseEvent } from './userBaseEvent';


export interface PaidEvent { 
    who: string;
    _with: PaidEventAllOfWith;
    what: PaidEvent.WhatEnum;
}
export namespace PaidEvent {
    export type WhatEnum = 'Paid';
    export const WhatEnum = {
        Paid: 'Paid' as WhatEnum
    };
}


