/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserBaseEvent } from './userBaseEvent';
import { RequestRefuntEventAllOf } from './requestRefuntEventAllOf';
import { RequestRefuntEventAllOfWith } from './requestRefuntEventAllOfWith';


export interface RequestRefuntEvent { 
    who: string;
    _with: RequestRefuntEventAllOfWith;
    what: RequestRefuntEvent.WhatEnum;
}
export namespace RequestRefuntEvent {
    export type WhatEnum = 'RefundRequested';
    export const WhatEnum = {
        RefundRequested: 'RefundRequested' as WhatEnum
    };
}


