http:
  port: 3001
admin:
  port: 9876
  host: localhost
apiEndpoints:
  product:
    host: localhost
    paths: ['/product','/product/*']
  order:
    host: localhost    
    paths: ['/order','/order/*']
  frontend:
    host: localhost    
    paths: '*'

serviceEndpoints:
  product:
    url: 'http://localhost:3003/'
  order:
    url: 'http://localhost:3002/'
  frontend:
    url: 'http://localhost:3000/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - frontend
    policies:
      - log: # policy name
        - action:    # array of condition/actions objects
            message: frontend ${req.method} ${req.originalUrl} # parameter for log action
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: frontend 
              changeOrigin: true
  orderPipeline:
    apiEndpoints:
      - order
    policies:
      - log: # policy name
          - action:    # array of condition/actions objects
              message: order ${req} ${req.method} ${req.originalUrl} # parameter for log action
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: order 
              stripPath: true
              changeOrigin: true
              prependPath: false
  productPipeline:
    apiEndpoints:
      - product
    policies:
      - log: # policy name
          - action:    # array of condition/actions objects
              message: product ${req.method} ${req.originalUrl} # parameter for log action
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: product 
              stripPath: true
              changeOrigin: true
              prependPath: false
