
http:
  port: 3000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  product:
    host: localhost
    paths: ['/product','/product/*']
  product-swagger:
    host: localhost    
    paths: ['/swagger/product/*']
  order:
    host: localhost    
    paths: ['/order','/order/*']
  order-swagger:
    host: localhost    
    paths: ['/swagger/order/*']
  frontend:
    host: localhost    
    paths: '*'

serviceEndpoints:
  product:
    url: "http://${PRODUCT_MICROSERVICE_SERVICE_SERVICE_HOST:-localhost}:3002/"
  order:
    url: "http://${ORDER_MICROSERVICE_SERVICE_SERVICE_HOST:-localhost}:3001/"
  frontend:
    url: "http://${FRONTEND_MICROSERVICE_SERVICE_SERVICE_HOST:-localhost}:${FRONTEND_MICROSERVICE_SERVICE_SERVICE_PORT:-3003}/"
policies:
  #- cors
  #- expression
  - log
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - frontend
    policies:
      - log: # policy name
        - action:    # array of condition/actions objects
            message: frontend ${req.method} ${req.originalUrl} # parameter for log action
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: frontend 
              changeOrigin: true
  orderPipeline:
    apiEndpoints:
      - order
    policies:
      - log: # policy name
          - action:    # array of condition/actions objects
              message: order ${req} ${req.method} ${req.originalUrl} # parameter for log action
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: order 
              changeOrigin: true
  orderSwaggerPipeline:
    apiEndpoints:
      - order-swagger
    policies:
      - log: # policy name
          - action:    # array of condition/actions objects
              message: order-swagger ${req} ${req.method} ${req.originalUrl} # parameter for log action
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: order 
              changeOrigin: true
              prependPath: true
              stripPath: true
  productPipeline:
    apiEndpoints:
      - product
    policies:
      - log: # policy name
          - action:    # array of condition/actions objects
              message: product ${req.method} ${req.originalUrl} # parameter for log action
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: product 
              changeOrigin: true
  productSwaggerPipeline:
    apiEndpoints:
      - product-swagger
    policies:
      - log: # policy name
          - action:    # array of condition/actions objects
              message: product-swagger ${req.method} ${req.originalUrl} # parameter for log action
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: product 
              prependPath: true
              stripPath: true
              changeOrigin: true


