http:
  port: 3000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  product:
    host: localhost
    paths: ['/product','/product/*']
  order:
    host: localhost    
    paths: ['/order','/order/*']
  frontend:
    host: localhost    
    paths: '*'

serviceEndpoints:
  product:
    url: 'http://host.docker.internal:1114/'
  order:
    url: 'http://host.docker.internal:1113/'
  frontend:
    url: 'http://host.docker.internal:1111/'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - frontend
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: frontend 
              changeOrigin: true
  orderPipeline:
    apiEndpoints:
      - order
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: order 
              changeOrigin: true
  productPipeline:
    apiEndpoints:
      - product
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: product 
              changeOrigin: true
