/* tslint:disable */
/* eslint-disable */
/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BadResponse
 */
export interface BadResponse {
    /**
     * 
     * @type {string}
     * @memberof BadResponse
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof BadResponse
     */
    error: BadResponseErrorEnum;
}

export function BadResponseFromJSON(json: any): BadResponse {
    return BadResponseFromJSONTyped(json, false);
}

export function BadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BadResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'error': json['error'],
    };
}

export function BadResponseToJSON(value?: BadResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'error': value.error,
    };
}

/**
* @export
* @enum {string}
*/
export enum BadResponseErrorEnum {
    True = 'true'
}


