/* tslint:disable */
/* eslint-disable */
/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BadResponse,
    BadResponseFromJSON,
    BadResponseFromJSONTyped,
    BadResponseToJSON,
    OkResponseProduct,
    OkResponseProductFromJSON,
    OkResponseProductFromJSONTyped,
    OkResponseProductToJSON,
    Product,
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './';

/**
 * 
 * @export
 * @interface ErrorResponseProduct
 */
export interface ErrorResponseProduct {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseProduct
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseProduct
     */
    error: ErrorResponseProductErrorEnum;
    /**
     * 
     * @type {Product}
     * @memberof ErrorResponseProduct
     */
    data: Product;
}

export function ErrorResponseProductFromJSON(json: any): ErrorResponseProduct {
    return ErrorResponseProductFromJSONTyped(json, false);
}

export function ErrorResponseProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseProduct {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'error': json['error'],
        'data': ProductFromJSON(json['data']),
    };
}

export function ErrorResponseProductToJSON(value?: ErrorResponseProduct | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'error': value.error,
        'data': ProductToJSON(value.data),
    };
}

/**
* @export
* @enum {string}
*/
export enum ErrorResponseProductErrorEnum {
    False = 'false'
}


