/* tslint:disable */
/* eslint-disable */
/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BadResponse,
    BadResponseFromJSON,
    BadResponseFromJSONTyped,
    BadResponseToJSON,
    OkResponseEmpty,
    OkResponseEmptyFromJSON,
    OkResponseEmptyFromJSONTyped,
    OkResponseEmptyToJSON,
} from './';

/**
 * 
 * @export
 * @interface ErrorResponseEmpty
 */
export interface ErrorResponseEmpty {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseEmpty
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseEmpty
     */
    error: ErrorResponseEmptyErrorEnum;
    /**
     * 
     * @type {object}
     * @memberof ErrorResponseEmpty
     */
    data: object;
}

export function ErrorResponseEmptyFromJSON(json: any): ErrorResponseEmpty {
    return ErrorResponseEmptyFromJSONTyped(json, false);
}

export function ErrorResponseEmptyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseEmpty {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'error': json['error'],
        'data': json['data'],
    };
}

export function ErrorResponseEmptyToJSON(value?: ErrorResponseEmpty | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'error': value.error,
        'data': value.data,
    };
}

/**
* @export
* @enum {string}
*/
export enum ErrorResponseEmptyErrorEnum {
    False = 'false'
}


