/* tslint:disable */
/* eslint-disable */
/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Product,
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './';

/**
 * 
 * @export
 * @interface OkResponseProduct
 */
export interface OkResponseProduct {
    /**
     * 
     * @type {Product}
     * @memberof OkResponseProduct
     */
    data: Product;
    /**
     * 
     * @type {boolean}
     * @memberof OkResponseProduct
     */
    error: OkResponseProductErrorEnum;
}

export function OkResponseProductFromJSON(json: any): OkResponseProduct {
    return OkResponseProductFromJSONTyped(json, false);
}

export function OkResponseProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): OkResponseProduct {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ProductFromJSON(json['data']),
        'error': json['error'],
    };
}

export function OkResponseProductToJSON(value?: OkResponseProduct | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ProductToJSON(value.data),
        'error': value.error,
    };
}

/**
* @export
* @enum {string}
*/
export enum OkResponseProductErrorEnum {
    False = 'false'
}


