/* tslint:disable */
/* eslint-disable */
/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProductDto,
    ProductDtoFromJSON,
    ProductDtoFromJSONTyped,
    ProductDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface OkResponseProductDtoArray
 */
export interface OkResponseProductDtoArray {
    /**
     * 
     * @type {Array<ProductDto>}
     * @memberof OkResponseProductDtoArray
     */
    data: Array<ProductDto>;
    /**
     * 
     * @type {boolean}
     * @memberof OkResponseProductDtoArray
     */
    error: OkResponseProductDtoArrayErrorEnum;
}

export function OkResponseProductDtoArrayFromJSON(json: any): OkResponseProductDtoArray {
    return OkResponseProductDtoArrayFromJSONTyped(json, false);
}

export function OkResponseProductDtoArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): OkResponseProductDtoArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ProductDtoFromJSON)),
        'error': json['error'],
    };
}

export function OkResponseProductDtoArrayToJSON(value?: OkResponseProductDtoArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(ProductDtoToJSON)),
        'error': value.error,
    };
}

/**
* @export
* @enum {string}
*/
export enum OkResponseProductDtoArrayErrorEnum {
    False = 'false'
}


