/* tslint:disable */
/* eslint-disable */
/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OkResponseEmpty
 */
export interface OkResponseEmpty {
    /**
     * 
     * @type {object}
     * @memberof OkResponseEmpty
     */
    data: object;
    /**
     * 
     * @type {boolean}
     * @memberof OkResponseEmpty
     */
    error: OkResponseEmptyErrorEnum;
}

export function OkResponseEmptyFromJSON(json: any): OkResponseEmpty {
    return OkResponseEmptyFromJSONTyped(json, false);
}

export function OkResponseEmptyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OkResponseEmpty {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': json['data'],
        'error': json['error'],
    };
}

export function OkResponseEmptyToJSON(value?: OkResponseEmpty | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': value.data,
        'error': value.error,
    };
}

/**
* @export
* @enum {string}
*/
export enum OkResponseEmptyErrorEnum {
    False = 'false'
}


