/* tslint:disable */
/* eslint-disable */
/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProductEventUnion,
    ProductEventUnionFromJSON,
    ProductEventUnionFromJSONTyped,
    ProductEventUnionToJSON,
} from './';

/**
 * 
 * @export
 * @interface OkResponseProductEventUnionArray
 */
export interface OkResponseProductEventUnionArray {
    /**
     * 
     * @type {Array<ProductEventUnion>}
     * @memberof OkResponseProductEventUnionArray
     */
    data: Array<ProductEventUnion>;
    /**
     * 
     * @type {boolean}
     * @memberof OkResponseProductEventUnionArray
     */
    error: OkResponseProductEventUnionArrayErrorEnum;
}

export function OkResponseProductEventUnionArrayFromJSON(json: any): OkResponseProductEventUnionArray {
    return OkResponseProductEventUnionArrayFromJSONTyped(json, false);
}

export function OkResponseProductEventUnionArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): OkResponseProductEventUnionArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(ProductEventUnionFromJSON)),
        'error': json['error'],
    };
}

export function OkResponseProductEventUnionArrayToJSON(value?: OkResponseProductEventUnionArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(ProductEventUnionToJSON)),
        'error': value.error,
    };
}

/**
* @export
* @enum {string}
*/
export enum OkResponseProductEventUnionArrayErrorEnum {
    False = 'false'
}


