/* tslint:disable */
/* eslint-disable */
/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Product,
    ProductFromJSON,
    ProductFromJSONTyped,
    ProductToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductEventUnionAnyOf
 */
export interface ProductEventUnionAnyOf {
    /**
     * 
     * @type {Product}
     * @memberof ProductEventUnionAnyOf
     */
    _with: Product;
    /**
     * 
     * @type {string}
     * @memberof ProductEventUnionAnyOf
     */
    what: ProductEventUnionAnyOfWhatEnum;
}

export function ProductEventUnionAnyOfFromJSON(json: any): ProductEventUnionAnyOf {
    return ProductEventUnionAnyOfFromJSONTyped(json, false);
}

export function ProductEventUnionAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductEventUnionAnyOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_with': ProductFromJSON(json['with']),
        'what': json['what'],
    };
}

export function ProductEventUnionAnyOfToJSON(value?: ProductEventUnionAnyOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'with': ProductToJSON(value._with),
        'what': value.what,
    };
}

/**
* @export
* @enum {string}
*/
export enum ProductEventUnionAnyOfWhatEnum {
    Changed = 'Changed'
}


