/* tslint:disable */
/* eslint-disable */
/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProductQuantity
 */
export interface ProductQuantity {
    /**
     * 
     * @type {number}
     * @memberof ProductQuantity
     */
    quantity: number;
}

export function ProductQuantityFromJSON(json: any): ProductQuantity {
    return ProductQuantityFromJSONTyped(json, false);
}

export function ProductQuantityFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductQuantity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'quantity': json['quantity'],
    };
}

export function ProductQuantityToJSON(value?: ProductQuantity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'quantity': value.quantity,
    };
}


