/* tslint:disable */
/* eslint-disable */
/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Product
 */
export interface Product {
    /**
     * 
     * @type {Array<string>}
     * @memberof Product
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    image: string;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    price: number;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof Product
     */
    shortDescription: string;
    /**
     * 
     * @type {number}
     * @memberof Product
     */
    quantity: number;
}

export function ProductFromJSON(json: any): Product {
    return ProductFromJSONTyped(json, false);
}

export function ProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): Product {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tags': json['tags'],
        'image': json['image'],
        'price': json['price'],
        'description': json['description'],
        'shortDescription': json['shortDescription'],
        'quantity': json['quantity'],
    };
}

export function ProductToJSON(value?: Product | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tags': value.tags,
        'image': value.image,
        'price': value.price,
        'description': value.description,
        'shortDescription': value.shortDescription,
        'quantity': value.quantity,
    };
}


