/* tslint:disable */
/* eslint-disable */
/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProductQuantity,
    ProductQuantityFromJSON,
    ProductQuantityFromJSONTyped,
    ProductQuantityToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductEventUnionAnyOf2
 */
export interface ProductEventUnionAnyOf2 {
    /**
     * 
     * @type {ProductQuantity}
     * @memberof ProductEventUnionAnyOf2
     */
    _with: ProductQuantity;
    /**
     * 
     * @type {string}
     * @memberof ProductEventUnionAnyOf2
     */
    what: ProductEventUnionAnyOf2WhatEnum;
}

export function ProductEventUnionAnyOf2FromJSON(json: any): ProductEventUnionAnyOf2 {
    return ProductEventUnionAnyOf2FromJSONTyped(json, false);
}

export function ProductEventUnionAnyOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductEventUnionAnyOf2 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_with': ProductQuantityFromJSON(json['with']),
        'what': json['what'],
    };
}

export function ProductEventUnionAnyOf2ToJSON(value?: ProductEventUnionAnyOf2 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'with': ProductQuantityToJSON(value._with),
        'what': value.what,
    };
}

/**
* @export
* @enum {string}
*/
export enum ProductEventUnionAnyOf2WhatEnum {
    Added = 'Added'
}


