apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-gateway-microservice-deployment
  labels:
    app: app-gateway-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-gateway-microservice
  template:
    metadata:
      labels:
        app: app-gateway-microservice
    spec:
      containers:
      - name: app-gateway-microservice
        image: docker.local:5000/app-gateway-microservice:latest
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: '3000'
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: app-gateway-microservice-service
spec:
  selector:
    app: app-gateway-microservice
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer