apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-microservice-deployment
  labels:
    app: frontend-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-microservice
  template:
    metadata:
      labels:
        app: frontend-microservice
    spec:
      containers:
      - name: frontend-microservice
        image: docker.local:5000/frontend-microservice:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-microservice-service
spec:
  selector:
    app: frontend-microservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort