apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-microservice-deployment
  labels:
    app: order-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-microservice
  template:
    metadata:
      labels:
        app: order-microservice
    spec:
      containers:
      - name: order-microservice
        image: docker.local:5000/order-microservice:latest
        ports:
        - containerPort: 3001
        env:
          - name: PORT
            value: '3001'
          - name: MONGO_DB
            value: 'mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017'
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: order-microservice-service
spec:
  selector:
    app: order-microservice
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: NodePort