/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AddressDto,
    AddressDtoFromJSON,
    AddressDtoFromJSONTyped,
    AddressDtoToJSON,
    AddressSetEventAllOf,
    AddressSetEventAllOfFromJSON,
    AddressSetEventAllOfFromJSONTyped,
    AddressSetEventAllOfToJSON,
    UserBaseEvent,
    UserBaseEventFromJSON,
    UserBaseEventFromJSONTyped,
    UserBaseEventToJSON,
} from './';

/**
 * 
 * @export
 * @interface AddressSetEvent
 */
export interface AddressSetEvent {
    /**
     * 
     * @type {string}
     * @memberof AddressSetEvent
     */
    who: string;
    /**
     * 
     * @type {AddressDto}
     * @memberof AddressSetEvent
     */
    _with: AddressDto;
    /**
     * 
     * @type {string}
     * @memberof AddressSetEvent
     */
    what: AddressSetEventWhatEnum;
}

export function AddressSetEventFromJSON(json: any): AddressSetEvent {
    return AddressSetEventFromJSONTyped(json, false);
}

export function AddressSetEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressSetEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'who': json['who'],
        '_with': AddressDtoFromJSON(json['with']),
        'what': json['what'],
    };
}

export function AddressSetEventToJSON(value?: AddressSetEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'who': value.who,
        'with': AddressDtoToJSON(value._with),
        'what': value.what,
    };
}

/**
* @export
* @enum {string}
*/
export enum AddressSetEventWhatEnum {
    AddressSet = 'AddressSet'
}


