/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AddressDto,
    AddressDtoFromJSON,
    AddressDtoFromJSONTyped,
    AddressDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface AddressSetEventAllOf
 */
export interface AddressSetEventAllOf {
    /**
     * 
     * @type {AddressDto}
     * @memberof AddressSetEventAllOf
     */
    _with: AddressDto;
    /**
     * 
     * @type {string}
     * @memberof AddressSetEventAllOf
     */
    what: AddressSetEventAllOfWhatEnum;
}

export function AddressSetEventAllOfFromJSON(json: any): AddressSetEventAllOf {
    return AddressSetEventAllOfFromJSONTyped(json, false);
}

export function AddressSetEventAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressSetEventAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_with': AddressDtoFromJSON(json['with']),
        'what': json['what'],
    };
}

export function AddressSetEventAllOfToJSON(value?: AddressSetEventAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'with': AddressDtoToJSON(value._with),
        'what': value.what,
    };
}

/**
* @export
* @enum {string}
*/
export enum AddressSetEventAllOfWhatEnum {
    AddressSet = 'AddressSet'
}


