/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BadResponse,
    BadResponseFromJSON,
    BadResponseFromJSONTyped,
    BadResponseToJSON,
    OkResponseNumber,
    OkResponseNumberFromJSON,
    OkResponseNumberFromJSONTyped,
    OkResponseNumberToJSON,
} from './';

/**
 * 
 * @export
 * @interface ErrorResponseNumber
 */
export interface ErrorResponseNumber {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseNumber
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseNumber
     */
    error: ErrorResponseNumberErrorEnum;
    /**
     * 
     * @type {number}
     * @memberof ErrorResponseNumber
     */
    data: number;
}

export function ErrorResponseNumberFromJSON(json: any): ErrorResponseNumber {
    return ErrorResponseNumberFromJSONTyped(json, false);
}

export function ErrorResponseNumberFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseNumber {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'error': json['error'],
        'data': json['data'],
    };
}

export function ErrorResponseNumberToJSON(value?: ErrorResponseNumber | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'error': value.error,
        'data': value.data,
    };
}

/**
* @export
* @enum {string}
*/
export enum ErrorResponseNumberErrorEnum {
    False = 'false'
}


