/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BadResponse,
    BadResponseFromJSON,
    BadResponseFromJSONTyped,
    BadResponseToJSON,
    OkResponseOrderDtoArray,
    OkResponseOrderDtoArrayFromJSON,
    OkResponseOrderDtoArrayFromJSONTyped,
    OkResponseOrderDtoArrayToJSON,
    OrderDto,
    OrderDtoFromJSON,
    OrderDtoFromJSONTyped,
    OrderDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface ErrorResponseOrderDtoArray
 */
export interface ErrorResponseOrderDtoArray {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseOrderDtoArray
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseOrderDtoArray
     */
    error: ErrorResponseOrderDtoArrayErrorEnum;
    /**
     * 
     * @type {Array<OrderDto>}
     * @memberof ErrorResponseOrderDtoArray
     */
    data: Array<OrderDto>;
}

export function ErrorResponseOrderDtoArrayFromJSON(json: any): ErrorResponseOrderDtoArray {
    return ErrorResponseOrderDtoArrayFromJSONTyped(json, false);
}

export function ErrorResponseOrderDtoArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseOrderDtoArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'error': json['error'],
        'data': ((json['data'] as Array<any>).map(OrderDtoFromJSON)),
    };
}

export function ErrorResponseOrderDtoArrayToJSON(value?: ErrorResponseOrderDtoArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'error': value.error,
        'data': ((value.data as Array<any>).map(OrderDtoToJSON)),
    };
}

/**
* @export
* @enum {string}
*/
export enum ErrorResponseOrderDtoArrayErrorEnum {
    False = 'false'
}


