/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BadResponse,
    BadResponseFromJSON,
    BadResponseFromJSONTyped,
    BadResponseToJSON,
    OkResponseOrderEventUnionArray,
    OkResponseOrderEventUnionArrayFromJSON,
    OkResponseOrderEventUnionArrayFromJSONTyped,
    OkResponseOrderEventUnionArrayToJSON,
    OrderEventUnion,
    OrderEventUnionFromJSON,
    OrderEventUnionFromJSONTyped,
    OrderEventUnionToJSON,
} from './';

/**
 * 
 * @export
 * @interface ErrorResponseOrderEventUnionArray
 */
export interface ErrorResponseOrderEventUnionArray {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseOrderEventUnionArray
     */
    message: string;
    /**
     * 
     * @type {boolean}
     * @memberof ErrorResponseOrderEventUnionArray
     */
    error: ErrorResponseOrderEventUnionArrayErrorEnum;
    /**
     * 
     * @type {Array<OrderEventUnion>}
     * @memberof ErrorResponseOrderEventUnionArray
     */
    data: Array<OrderEventUnion>;
}

export function ErrorResponseOrderEventUnionArrayFromJSON(json: any): ErrorResponseOrderEventUnionArray {
    return ErrorResponseOrderEventUnionArrayFromJSONTyped(json, false);
}

export function ErrorResponseOrderEventUnionArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseOrderEventUnionArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
        'error': json['error'],
        'data': ((json['data'] as Array<any>).map(OrderEventUnionFromJSON)),
    };
}

export function ErrorResponseOrderEventUnionArrayToJSON(value?: ErrorResponseOrderEventUnionArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'error': value.error,
        'data': ((value.data as Array<any>).map(OrderEventUnionToJSON)),
    };
}

/**
* @export
* @enum {string}
*/
export enum ErrorResponseOrderEventUnionArrayErrorEnum {
    False = 'false'
}


