/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Order,
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
} from './';

/**
 * 
 * @export
 * @interface IssuedEventAllOf
 */
export interface IssuedEventAllOf {
    /**
     * 
     * @type {Order}
     * @memberof IssuedEventAllOf
     */
    _with: Order;
    /**
     * 
     * @type {string}
     * @memberof IssuedEventAllOf
     */
    what: IssuedEventAllOfWhatEnum;
}

export function IssuedEventAllOfFromJSON(json: any): IssuedEventAllOf {
    return IssuedEventAllOfFromJSONTyped(json, false);
}

export function IssuedEventAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuedEventAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_with': OrderFromJSON(json['with']),
        'what': json['what'],
    };
}

export function IssuedEventAllOfToJSON(value?: IssuedEventAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'with': OrderToJSON(value._with),
        'what': value.what,
    };
}

/**
* @export
* @enum {string}
*/
export enum IssuedEventAllOfWhatEnum {
    Issued = 'Issued'
}


