/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    IssuedEventAllOf,
    IssuedEventAllOfFromJSON,
    IssuedEventAllOfFromJSONTyped,
    IssuedEventAllOfToJSON,
    Order,
    OrderFromJSON,
    OrderFromJSONTyped,
    OrderToJSON,
    UserBaseEvent,
    UserBaseEventFromJSON,
    UserBaseEventFromJSONTyped,
    UserBaseEventToJSON,
} from './';

/**
 * 
 * @export
 * @interface IssuedEvent
 */
export interface IssuedEvent {
    /**
     * 
     * @type {string}
     * @memberof IssuedEvent
     */
    who: string;
    /**
     * 
     * @type {Order}
     * @memberof IssuedEvent
     */
    _with: Order;
    /**
     * 
     * @type {string}
     * @memberof IssuedEvent
     */
    what: IssuedEventWhatEnum;
}

export function IssuedEventFromJSON(json: any): IssuedEvent {
    return IssuedEventFromJSONTyped(json, false);
}

export function IssuedEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): IssuedEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'who': json['who'],
        '_with': OrderFromJSON(json['with']),
        'what': json['what'],
    };
}

export function IssuedEventToJSON(value?: IssuedEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'who': value.who,
        'with': OrderToJSON(value._with),
        'what': value.what,
    };
}

/**
* @export
* @enum {string}
*/
export enum IssuedEventWhatEnum {
    Issued = 'Issued'
}


