/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrderEventUnion,
    OrderEventUnionFromJSON,
    OrderEventUnionFromJSONTyped,
    OrderEventUnionToJSON,
} from './';

/**
 * 
 * @export
 * @interface OkResponseOrderEventUnionArray
 */
export interface OkResponseOrderEventUnionArray {
    /**
     * 
     * @type {Array<OrderEventUnion>}
     * @memberof OkResponseOrderEventUnionArray
     */
    data: Array<OrderEventUnion>;
    /**
     * 
     * @type {boolean}
     * @memberof OkResponseOrderEventUnionArray
     */
    error: OkResponseOrderEventUnionArrayErrorEnum;
}

export function OkResponseOrderEventUnionArrayFromJSON(json: any): OkResponseOrderEventUnionArray {
    return OkResponseOrderEventUnionArrayFromJSONTyped(json, false);
}

export function OkResponseOrderEventUnionArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): OkResponseOrderEventUnionArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(OrderEventUnionFromJSON)),
        'error': json['error'],
    };
}

export function OkResponseOrderEventUnionArrayToJSON(value?: OkResponseOrderEventUnionArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(OrderEventUnionToJSON)),
        'error': value.error,
    };
}

/**
* @export
* @enum {string}
*/
export enum OkResponseOrderEventUnionArrayErrorEnum {
    False = 'false'
}


