/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrderDto,
    OrderDtoFromJSON,
    OrderDtoFromJSONTyped,
    OrderDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface OkResponseOrderDtoArray
 */
export interface OkResponseOrderDtoArray {
    /**
     * 
     * @type {Array<OrderDto>}
     * @memberof OkResponseOrderDtoArray
     */
    data: Array<OrderDto>;
    /**
     * 
     * @type {boolean}
     * @memberof OkResponseOrderDtoArray
     */
    error: OkResponseOrderDtoArrayErrorEnum;
}

export function OkResponseOrderDtoArrayFromJSON(json: any): OkResponseOrderDtoArray {
    return OkResponseOrderDtoArrayFromJSONTyped(json, false);
}

export function OkResponseOrderDtoArrayFromJSONTyped(json: any, ignoreDiscriminator: boolean): OkResponseOrderDtoArray {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(OrderDtoFromJSON)),
        'error': json['error'],
    };
}

export function OkResponseOrderDtoArrayToJSON(value?: OkResponseOrderDtoArray | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'data': ((value.data as Array<any>).map(OrderDtoToJSON)),
        'error': value.error,
    };
}

/**
* @export
* @enum {string}
*/
export enum OkResponseOrderDtoArrayErrorEnum {
    False = 'false'
}


