/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrdersAddresPaymentWriteModel
 */
export interface OrdersAddresPaymentWriteModel {
    /**
     * 
     * @type {string}
     * @memberof OrdersAddresPaymentWriteModel
     */
    paymentMethod: string;
    /**
     * 
     * @type {string}
     * @memberof OrdersAddresPaymentWriteModel
     */
    postalCode: string;
    /**
     * 
     * @type {string}
     * @memberof OrdersAddresPaymentWriteModel
     */
    country: string;
    /**
     * 
     * @type {string}
     * @memberof OrdersAddresPaymentWriteModel
     */
    street: string;
}

export function OrdersAddresPaymentWriteModelFromJSON(json: any): OrdersAddresPaymentWriteModel {
    return OrdersAddresPaymentWriteModelFromJSONTyped(json, false);
}

export function OrdersAddresPaymentWriteModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrdersAddresPaymentWriteModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'paymentMethod': json['paymentMethod'],
        'postalCode': json['postalCode'],
        'country': json['country'],
        'street': json['street'],
    };
}

export function OrdersAddresPaymentWriteModelToJSON(value?: OrdersAddresPaymentWriteModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'paymentMethod': value.paymentMethod,
        'postalCode': value.postalCode,
        'country': value.country,
        'street': value.street,
    };
}


