/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderProduct
 */
export interface OrderProduct {
    /**
     * 
     * @type {string}
     * @memberof OrderProduct
     */
    image: string;
    /**
     * 
     * @type {string}
     * @memberof OrderProduct
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof OrderProduct
     */
    shortDescription: string;
    /**
     * 
     * @type {number}
     * @memberof OrderProduct
     */
    price: number;
    /**
     * 
     * @type {number}
     * @memberof OrderProduct
     */
    totalPrice: number;
    /**
     * 
     * @type {number}
     * @memberof OrderProduct
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof OrderProduct
     */
    name: string;
}

export function OrderProductFromJSON(json: any): OrderProduct {
    return OrderProductFromJSONTyped(json, false);
}

export function OrderProductFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderProduct {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'image': json['image'],
        'description': json['description'],
        'shortDescription': json['shortDescription'],
        'price': json['price'],
        'totalPrice': json['totalPrice'],
        'quantity': json['quantity'],
        'name': json['name'],
    };
}

export function OrderProductToJSON(value?: OrderProduct | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image': value.image,
        'description': value.description,
        'shortDescription': value.shortDescription,
        'price': value.price,
        'totalPrice': value.totalPrice,
        'quantity': value.quantity,
        'name': value.name,
    };
}


