/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PaidEventAllOf,
    PaidEventAllOfFromJSON,
    PaidEventAllOfFromJSONTyped,
    PaidEventAllOfToJSON,
    PaidEventAllOfWith,
    PaidEventAllOfWithFromJSON,
    PaidEventAllOfWithFromJSONTyped,
    PaidEventAllOfWithToJSON,
    UserBaseEvent,
    UserBaseEventFromJSON,
    UserBaseEventFromJSONTyped,
    UserBaseEventToJSON,
} from './';

/**
 * 
 * @export
 * @interface PaidEvent
 */
export interface PaidEvent {
    /**
     * 
     * @type {string}
     * @memberof PaidEvent
     */
    who: string;
    /**
     * 
     * @type {PaidEventAllOfWith}
     * @memberof PaidEvent
     */
    _with: PaidEventAllOfWith;
    /**
     * 
     * @type {string}
     * @memberof PaidEvent
     */
    what: PaidEventWhatEnum;
}

export function PaidEventFromJSON(json: any): PaidEvent {
    return PaidEventFromJSONTyped(json, false);
}

export function PaidEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaidEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'who': json['who'],
        '_with': PaidEventAllOfWithFromJSON(json['with']),
        'what': json['what'],
    };
}

export function PaidEventToJSON(value?: PaidEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'who': value.who,
        'with': PaidEventAllOfWithToJSON(value._with),
        'what': value.what,
    };
}

/**
* @export
* @enum {string}
*/
export enum PaidEventWhatEnum {
    Paid = 'Paid'
}


