/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaidEventAllOfWith
 */
export interface PaidEventAllOfWith {
    /**
     * 
     * @type {string}
     * @memberof PaidEventAllOfWith
     */
    method: string;
    /**
     * 
     * @type {number}
     * @memberof PaidEventAllOfWith
     */
    amount: number;
}

export function PaidEventAllOfWithFromJSON(json: any): PaidEventAllOfWith {
    return PaidEventAllOfWithFromJSONTyped(json, false);
}

export function PaidEventAllOfWithFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaidEventAllOfWith {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'method': json['method'],
        'amount': json['amount'],
    };
}

export function PaidEventAllOfWithToJSON(value?: PaidEventAllOfWith | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'method': value.method,
        'amount': value.amount,
    };
}


