/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefundEventAllOfWith
 */
export interface RefundEventAllOfWith {
    /**
     * 
     * @type {string}
     * @memberof RefundEventAllOfWith
     */
    cause: string;
}

export function RefundEventAllOfWithFromJSON(json: any): RefundEventAllOfWith {
    return RefundEventAllOfWithFromJSONTyped(json, false);
}

export function RefundEventAllOfWithFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundEventAllOfWith {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cause': json['cause'],
    };
}

export function RefundEventAllOfWithToJSON(value?: RefundEventAllOfWith | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cause': value.cause,
    };
}


