/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RefundEventAllOfWith,
    RefundEventAllOfWithFromJSON,
    RefundEventAllOfWithFromJSONTyped,
    RefundEventAllOfWithToJSON,
} from './';

/**
 * 
 * @export
 * @interface RefundEventAllOf
 */
export interface RefundEventAllOf {
    /**
     * 
     * @type {RefundEventAllOfWith}
     * @memberof RefundEventAllOf
     */
    _with: RefundEventAllOfWith;
    /**
     * 
     * @type {string}
     * @memberof RefundEventAllOf
     */
    what: RefundEventAllOfWhatEnum;
}

export function RefundEventAllOfFromJSON(json: any): RefundEventAllOf {
    return RefundEventAllOfFromJSONTyped(json, false);
}

export function RefundEventAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefundEventAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_with': RefundEventAllOfWithFromJSON(json['with']),
        'what': json['what'],
    };
}

export function RefundEventAllOfToJSON(value?: RefundEventAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'with': RefundEventAllOfWithToJSON(value._with),
        'what': value.what,
    };
}

/**
* @export
* @enum {string}
*/
export enum RefundEventAllOfWhatEnum {
    Refunded = 'Refunded'
}


