/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RequestRefuntEventAllOfWith,
    RequestRefuntEventAllOfWithFromJSON,
    RequestRefuntEventAllOfWithFromJSONTyped,
    RequestRefuntEventAllOfWithToJSON,
} from './';

/**
 * 
 * @export
 * @interface RequestRefuntEventAllOf
 */
export interface RequestRefuntEventAllOf {
    /**
     * 
     * @type {RequestRefuntEventAllOfWith}
     * @memberof RequestRefuntEventAllOf
     */
    _with: RequestRefuntEventAllOfWith;
    /**
     * 
     * @type {string}
     * @memberof RequestRefuntEventAllOf
     */
    what: RequestRefuntEventAllOfWhatEnum;
}

export function RequestRefuntEventAllOfFromJSON(json: any): RequestRefuntEventAllOf {
    return RequestRefuntEventAllOfFromJSONTyped(json, false);
}

export function RequestRefuntEventAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestRefuntEventAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_with': RequestRefuntEventAllOfWithFromJSON(json['with']),
        'what': json['what'],
    };
}

export function RequestRefuntEventAllOfToJSON(value?: RequestRefuntEventAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'with': RequestRefuntEventAllOfWithToJSON(value._with),
        'what': value.what,
    };
}

/**
* @export
* @enum {string}
*/
export enum RequestRefuntEventAllOfWhatEnum {
    RefundRequested = 'RefundRequested'
}


