/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RequestRefuntEventAllOfWith
 */
export interface RequestRefuntEventAllOfWith {
    /**
     * 
     * @type {string}
     * @memberof RequestRefuntEventAllOfWith
     */
    refundCause: string;
}

export function RequestRefuntEventAllOfWithFromJSON(json: any): RequestRefuntEventAllOfWith {
    return RequestRefuntEventAllOfWithFromJSONTyped(json, false);
}

export function RequestRefuntEventAllOfWithFromJSONTyped(json: any, ignoreDiscriminator: boolean): RequestRefuntEventAllOfWith {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'refundCause': json['refundCause'],
    };
}

export function RequestRefuntEventAllOfWithToJSON(value?: RequestRefuntEventAllOfWith | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'refundCause': value.refundCause,
    };
}


