/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SentEventAllOf,
    SentEventAllOfFromJSON,
    SentEventAllOfFromJSONTyped,
    SentEventAllOfToJSON,
    UserBaseEvent,
    UserBaseEventFromJSON,
    UserBaseEventFromJSONTyped,
    UserBaseEventToJSON,
} from './';

/**
 * 
 * @export
 * @interface SentEvent
 */
export interface SentEvent {
    /**
     * 
     * @type {string}
     * @memberof SentEvent
     */
    who: string;
    /**
     * 
     * @type {object}
     * @memberof SentEvent
     */
    _with: object;
    /**
     * 
     * @type {string}
     * @memberof SentEvent
     */
    what: SentEventWhatEnum;
}

export function SentEventFromJSON(json: any): SentEvent {
    return SentEventFromJSONTyped(json, false);
}

export function SentEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): SentEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'who': json['who'],
        '_with': json['with'],
        'what': json['what'],
    };
}

export function SentEventToJSON(value?: SentEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'who': value.who,
        'with': value._with,
        'what': value.what,
    };
}

/**
* @export
* @enum {string}
*/
export enum SentEventWhatEnum {
    Sent = 'Sent'
}


