/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SentEventAllOf
 */
export interface SentEventAllOf {
    /**
     * 
     * @type {object}
     * @memberof SentEventAllOf
     */
    _with: object;
    /**
     * 
     * @type {string}
     * @memberof SentEventAllOf
     */
    what: SentEventAllOfWhatEnum;
}

export function SentEventAllOfFromJSON(json: any): SentEventAllOf {
    return SentEventAllOfFromJSONTyped(json, false);
}

export function SentEventAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): SentEventAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_with': json['with'],
        'what': json['what'],
    };
}

export function SentEventAllOfToJSON(value?: SentEventAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'with': value._with,
        'what': value.what,
    };
}

/**
* @export
* @enum {string}
*/
export enum SentEventAllOfWhatEnum {
    Sent = 'Sent'
}


