/* tslint:disable */
/* eslint-disable */
/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserBaseEvent
 */
export interface UserBaseEvent {
    /**
     * 
     * @type {string}
     * @memberof UserBaseEvent
     */
    who: string;
}

export function UserBaseEventFromJSON(json: any): UserBaseEvent {
    return UserBaseEventFromJSONTyped(json, false);
}

export function UserBaseEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBaseEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'who': json['who'],
    };
}

export function UserBaseEventToJSON(value?: UserBaseEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'who': value.who,
    };
}


