/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorResponseProductEventUnionArrayAnyOf } from './errorResponseProductEventUnionArrayAnyOf';
import { ErrorResponseProductDtoArrayAnyOf } from './errorResponseProductDtoArrayAnyOf';
import { ProductDto } from './productDto';


export interface ErrorResponseProductDtoArray { 
    message: string;
    error: ErrorResponseProductDtoArray.ErrorEnum;
    data: Array<ProductDto>;
}
export namespace ErrorResponseProductDtoArray {
    export type ErrorEnum = 'false';
    export const ErrorEnum = {
        False: 'false' as ErrorEnum
    };
}


