/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ErrorResponseProductEventUnionArrayAnyOf } from './errorResponseProductEventUnionArrayAnyOf';
import { Product } from './product';
import { ErrorResponseProductAnyOf } from './errorResponseProductAnyOf';


export interface ErrorResponseProduct { 
    message: string;
    error: ErrorResponseProduct.ErrorEnum;
    data: Product;
}
export namespace ErrorResponseProduct {
    export type ErrorEnum = 'false';
    export const ErrorEnum = {
        False: 'false' as ErrorEnum
    };
}


