/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Order } from './order';
import { OrderDtoAllOf } from './orderDtoAllOf';
import { OrderProduct } from './orderProduct';


export interface OrderDto { 
    products: Array<OrderProduct>;
    name: string;
    quantity: number;
    status: OrderDto.StatusEnum;
    id?: string;
}
export namespace OrderDto {
    export type StatusEnum = 'Started' | 'Sent' | 'Derived' | 'Returned';
    export const StatusEnum = {
        Started: 'Started' as StatusEnum,
        Sent: 'Sent' as StatusEnum,
        Derived: 'Derived' as StatusEnum,
        Returned: 'Returned' as StatusEnum
    };
}


