/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaidEventAllOfWith } from './paidEventAllOfWith';


export interface PaidEventAllOf { 
    _with: PaidEventAllOfWith;
    what: PaidEventAllOf.WhatEnum;
}
export namespace PaidEventAllOf {
    export type WhatEnum = 'Paid';
    export const WhatEnum = {
        Paid: 'Paid' as WhatEnum
    };
}


