/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';


export interface ProductEventUnionAnyOf { 
    _with: Product;
    what: ProductEventUnionAnyOf.WhatEnum;
}
export namespace ProductEventUnionAnyOf {
    export type WhatEnum = 'Changed';
    export const WhatEnum = {
        Changed: 'Changed' as WhatEnum
    };
}


