/**
 * product-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductQuantity } from './productQuantity';
import { ProductEventUnionAnyOf2 } from './productEventUnionAnyOf2';
import { ProductEventUnionAnyOf1 } from './productEventUnionAnyOf1';
import { ProductEventUnionAnyOf } from './productEventUnionAnyOf';
import { ProductEventUnionAnyOf3 } from './productEventUnionAnyOf3';


export interface ProductEventUnion { 
    _with: ProductQuantity;
    what: ProductEventUnion.WhatEnum;
}
export namespace ProductEventUnion {
    export type WhatEnum = 'Bought';
    export const WhatEnum = {
        Bought: 'Bought' as WhatEnum
    };
}


