/**
 * order-microservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestRefuntEventAllOfWith } from './requestRefuntEventAllOfWith';


export interface RequestRefuntEventAllOf { 
    _with: RequestRefuntEventAllOfWith;
    what: RequestRefuntEventAllOf.WhatEnum;
}
export namespace RequestRefuntEventAllOf {
    export type WhatEnum = 'RefundRequested';
    export const WhatEnum = {
        RefundRequested: 'RefundRequested' as WhatEnum
    };
}


