name: build-and-publish-product-microservice

on:
  push:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.22
      with:
        name: pixellos/agh.6.sr.to_node_1/order-microservice
        registry: docker.pkg.github.com
        username: ${{ secrets.USERNAMEGH }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: product-microservice/Dockerfile-prod
        tags: ${{ github.sha }}
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'agh-sr-exp1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_ContainerUsername_03139864d557486caff9bc0ed9d9b951 }}
        images: 'docker.pkg.github.com/pixellos/agh.6.sr.to_node_1/order-microservice:${{ github.sha }}'
