name: frontend-microservice

on:
  push:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 14.13
      uses: actions/setup-node@v1
      with:
        node-version: '14.13'
    - name: restore & build
      env:
        CI: true
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.22
      with:
        name: pixellos/agh.6.sr.to_node_1/frontend-microservice
        registry: docker.pkg.github.com
        username: ${{ secrets.USERNAMEGH }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: frontend/Dockerfile
        tags: ${{ github.sha }}
