name: product-microservice

on:
  push:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.22
      with:
        name: pixellos/agh.6.sr.to_node_1/product-microservice
        registry: docker.pkg.github.com
        username: ${{ secrets.USERNAMEGH }}
        password: ${{ secrets.GITHUB_TOKEN }}
        dockerfile: product-microservice/Dockerfile-prod
        tags: ${{ github.sha }}
  